name: Build TWRP Recovery - Beryllium

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ROM_LOCAL_MANIFEST: .repo/local_manifests
      DEVICE_CODENAME: beryllium
      DEVICE_TREE_REPO: https://github.com/Abudfu/twrp_xiaomi_beryllium
      DEVICE_TREE_BRANCH: android-12.1

    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc \
            python3 python3-pip openjdk-8-jdk python-is-python3 schedtool ccache lzop imagemagick jq liblz4-tool \
            pngcrush libncurses5 python3-distutils python3-apt repo
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

      - name: Check out manifest & init repo
        run: |
          mkdir -p ~/workspace && cd ~/workspace
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          # Init repo (minimal-manifest-twrp)
          git clone https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-14.1 .repo/manifests
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1 --depth=1
        working-directory: ${{ github.workspace }}

      - name: Sync sources
        run: |
          cd ~/workspace
          repo sync -j$(nproc) --force-sync

      - name: Clone device tree
        run: |
          cd ~/workspace
          mkdir -p device/xiaomi
          git clone --depth=1 https://github.com/${DEVICE_TREE_REPO}.git -b ${DEVICE_TREE_BRANCH} device/xiaomi/${DEVICE_CODENAME}

      - name: Clone recovery source
        run: |
          cd ~/workspace
          mkdir -p bootable/recovery
          git clone --depth=1 https://github.com/Abudfu/twrp_xiaomi_beryllium.git bootable/recovery

      - name: Setup ccache (optional)
        uses: actions/cache@v4
        with:
          path: ~/workspace/.ccache
          key: ${{ runner.os }}-ccache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build TWRP
        run: |
          cd ~/workspace
          export ALLOW_MISSING_DEPENDENCIES=true
          export CCACHE_EXEC=$(which ccache)
          export USE_CCACHE=1
          ccache -M 20G
          source build/envsetup.sh
          lunch twrp_${DEVICE_CODENAME}-eng
          mka recoveryimage
        shell: bash

      - name: Upload recovery image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-beryllium-recovery
          path: |
            ~/workspace/out/target/product/${{ env.DEVICE_CODENAME }}/recovery.img
